name: Fetch Native Dependencies
on: [workflow_dispatch]

jobs:
  fetch-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Fetch Script
        run: |
          chmod +x scripts/build_deps.sh
          ./scripts/build_deps.sh
      - name: Commit Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add pre-built native binaries"
          
